<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Huiyi Zhu" />

<meta name="date" content="2025-12-04" />

<title>data clean</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="Descriptive_Analysis.html">Data Exploration</a>
</li>
<li>
  <a href="Data_Analysis.html">Data Analysis</a>
</li>
<li>
  <a href="Model.html">Model</a>
</li>
<li>
  <a href="Project_Report.html">Project Report</a>
</li>
<li>
  <a href="mailto:&lt;you@youremail.com&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/Huiyi-hz3023/Final-Project">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">data clean</h1>
<h4 class="author">Huiyi Zhu</h4>
<h4 class="date">2025-12-04</h4>

</div>


<div id="prepare" class="section level2">
<h2>prepare</h2>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.0     ✔ stringr   1.5.1
## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
## ✔ purrr     1.1.0     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<pre class="r"><code>library(janitor)</code></pre>
<pre><code>## 
## Attaching package: &#39;janitor&#39;
## 
## The following objects are masked from &#39;package:stats&#39;:
## 
##     chisq.test, fisher.test</code></pre>
<pre class="r"><code>library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(broom)</code></pre>
<p>outcome: attendance variables: season, event type, borough, location
type, time of date</p>
<p>Miranda Chen: model (before 11:59PM Friday) Huiyi Zhu: clean data
(date:2022.5-present, morning5-12 afternoon 12-6 night 6-1 midnight?) +
basic descriptive analysis Yiyang Jiao: report+video (9:00PM Sat)
Xiaoqian Lyu: report Yuyue Ma: web(sat)</p>
<pre class="r"><code>raw = read.csv(&quot;Parks_Special_Events_20251204.csv&quot;)</code></pre>
</div>
<div id="data-cleaning" class="section level2">
<h2>Data Cleaning</h2>
<pre class="r"><code>parkevent = read.csv(&quot;Parks_Special_Events_20251204.csv&quot;) |&gt;
  janitor::clean_names() |&gt;
  mutate(
    datetime = mdy_hms(date_and_time),
    date     = as_date(datetime), 
    year  = year(datetime),
    month = month(datetime, label = TRUE, abbr = TRUE),
    day = day(datetime),
    time = format(datetime, &quot;%H:%M:%S&quot;),
    season = case_when(
      month %in% c(&quot;Mar&quot;,&quot;Apr&quot;,&quot;May&quot;) ~ &quot;Spring&quot;,
      month %in% c(&quot;Jun&quot;,&quot;Jul&quot;,&quot;Aug&quot;) ~ &quot;Summer&quot;,
      month %in% c(&quot;Sep&quot;,&quot;Oct&quot;,&quot;Nov&quot;) ~ &quot;Fall&quot;,
      month %in% c(&quot;Dec&quot;,&quot;Jan&quot;,&quot;Feb&quot;) ~ &quot;Winter&quot;), 
      season = factor(season,
        levels = c(&quot;Spring&quot;, &quot;Summer&quot;, &quot;Fall&quot;, &quot;Winter&quot;)),
    hour = as.numeric(format(datetime, &quot;%H&quot;)),
    time_period = case_when(
      hour &lt; 5 ~ &quot;Midnight&quot;,
      hour &gt;= 5  &amp; hour &lt; 12 ~ &quot;Morning&quot;,
      hour &gt;= 12 &amp; hour &lt; 18 ~ &quot;Afternoon&quot;,
      hour &gt;= 18 &amp; hour &lt; 23 ~ &quot;Night&quot;,
      hour &gt;= 23   ~ &quot;Midnight&quot;),
   time_period = factor(time_period,
                     levels = c(&quot;Morning&quot;, &quot;Afternoon&quot;, &quot;Night&quot;, &quot;Midnight&quot;)),
    attendance = as.numeric(attendance))|&gt;  
  
  mutate(
    aud_list = str_split(audience, &quot;;|,&quot;),
    aud_list = map(aud_list, ~ str_trim(.x)),
    has_children = map_lgl(aud_list, ~ any(.x %in% c(&quot;Children&quot;, &quot;Kids&quot;, &quot;Tot&quot;))),
    has_seniors  = map_lgl(aud_list, ~ any(.x %in% c(&quot;Seniors&quot;, &quot;Senior&quot;))),
    has_genpub   = map_lgl(aud_list, ~ any(.x == &quot;General Public&quot;)),
    
    kids_friendly   = has_children | has_genpub,
    senior_friendly = has_seniors  | has_genpub,
    adults_only     = !kids_friendly &amp; !senior_friendly)|&gt; 
  
  select(
    -datetime,
    -unit,
    -group_name_partner,
    -date_and_time,
    -classification,
    -source,
    -hour,
    -event_name,
    -location,
    -audience,
    -aud_list,
    -has_children,
    -has_seniors,
    - has_genpub) |&gt; 
  select(
    date, year, month, day, time, season,time_period, everything()) |&gt; 
    filter(date &gt;= as.Date(&quot;2021-06-01&quot;),
           event_type != &quot;&quot;,
           category != &quot;&quot;,
           attendance != &quot;&quot;)</code></pre>
<pre><code>## Warning: There was 1 warning in `mutate()`.
## ℹ In argument: `attendance = as.numeric(attendance)`.
## Caused by warning:
## ! NAs introduced by coercion</code></pre>
<p>We cleaned the dataset to prepare it for analyzing attendance as the
primary outcome and key predictors including season, event_type,
borough, location_type, and time_period. Date-time information was
parsed into date, year, month, and day to support temporal analyses, and
time_period was created to evaluate differences across times of day. We
filtered observations to the NYC fully reopened period after COVID (date
&gt;= “2021-06-01”) to avoid pandemic-related disruptions. Columns not
relevant to the analysis were removed, and rows with empty event_type,
category and attendance values were dropped. After cleaning, we have
2447 observations and 15 variables. These steps produced a tidy dataset
aligned with our study.</p>
<p>How we cleaned the audience type: We first standardized the audience
field by splitting each entry into individual audience categories (e.g.,
“Children,” “Adults,” “Seniors,” “General Public”). Based on these
cleaned components, we created three binary indicators to capture the
accessibility of each event to key demographic groups.</p>
<p>An event was classified as kids-friendly if its audience included
Children/Tot or was labeled as General Public. Similarly, an event was
marked as senior-friendly if Seniors were listed or if the audience was
General Public. Finally, we defined adults-only events as those not
classified as kids-friendly, meaning no child-oriented groups were
present in the audience description.</p>
<p>Dropped the unnecessary variables generated during the process</p>
<pre class="r"><code>parkevent %&gt;% count(kids_friendly)</code></pre>
<pre><code>##   kids_friendly    n
## 1         FALSE  252
## 2          TRUE 2195</code></pre>
<pre class="r"><code>parkevent %&gt;% count(senior_friendly)</code></pre>
<pre><code>##   senior_friendly    n
## 1           FALSE  718
## 2            TRUE 1729</code></pre>
<pre class="r"><code>parkevent %&gt;% count(adults_only)</code></pre>
<pre><code>##   adults_only    n
## 1       FALSE 2228
## 2        TRUE  219</code></pre>
</div>
<div id="descriptive-analysis" class="section level2">
<h2>Descriptive Analysis</h2>
<pre class="r"><code>parkevent |&gt;
  summarize(
    mean_attendance = mean(attendance),
    median_attendance = median(attendance),
    sd_attendance = sd(attendance),
    min_attendance = min(attendance),
    max_attendance = max(attendance)) |&gt;
  knitr::kable(digits = 2)</code></pre>
<table>
<colgroup>
<col width="20%" />
<col width="23%" />
<col width="17%" />
<col width="19%" />
<col width="19%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">mean_attendance</th>
<th align="right">median_attendance</th>
<th align="right">sd_attendance</th>
<th align="right">min_attendance</th>
<th align="right">max_attendance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">74.44</td>
<td align="right">39</td>
<td align="right">100.95</td>
<td align="right">0</td>
<td align="right">861</td>
</tr>
</tbody>
</table>
<p>This table summarizes the distribution of attendance across all
post-COVID events, including the mean, median, variability, and range of
turnout. These descriptive statistics provide an essential baseline for
understanding overall engagement levels and for comparing attendance
across seasons, event types, boroughs, and time-of-day categories in
subsequent analyses.</p>
<pre class="r"><code>plot_season =
  ggplot(parkevent, aes(x = season, y = attendance, fill=season)) +
  geom_violin(trim = FALSE, alpha = 0.5) +
  geom_boxplot(width=0.15) +
  coord_cartesian(ylim = c(0,250)) +
  scale_x_discrete(labels = c(
    &quot;Spring&quot; = &quot;Spr&quot;,
    &quot;Summer&quot; = &quot;Sum&quot;,
    &quot;Fall&quot;   = &quot;Fal&quot;,
    &quot;Winter&quot; = &quot;Win&quot;)) +
  labs(title = &quot;By Season&quot;, x = &quot;Season&quot;, y = &quot;Attendance&quot;) +
  guides(fill = &quot;none&quot;) +
  theme_minimal()

plot_time =
  ggplot(parkevent, aes(x = time_period, y = attendance, fill=time_period)) +
  geom_violin(trim = FALSE, alpha = 0.5) +
  geom_boxplot(width=0.15) +
  coord_cartesian(ylim = c(0,250)) +
  scale_x_discrete(labels = c(
    &quot;Morning&quot;   = &quot;Morn&quot;,
    &quot;Afternoon&quot; = &quot;Aft&quot;,
    &quot;Night&quot;     = &quot;Ngt&quot;,
    &quot;Midnight&quot;  = &quot;Mid&quot;)) +
  labs(title = &quot;By Time of Day&quot;, x = &quot;Time of Day&quot;, y = &quot;Attendance&quot;) +
  guides(fill = &quot;none&quot;) +
  theme_minimal()

plot_type =
  ggplot(parkevent, aes(x = event_type, y = attendance, fill = event_type)) +
  geom_violin(trim = FALSE, alpha = 0.5) +
  geom_boxplot(width = 0.15) +
  coord_cartesian(ylim = c(0,250)) +
  scale_x_discrete(labels = c(
    &quot;Agency Produced Event&quot; = &quot;Agency&quot;,
    &quot;Community Based Event&quot; = &quot;Community&quot;,
    &quot;Local Event&quot; = &quot;Local&quot;,
    &quot;Open House&quot; = &quot;Open&quot;,
    &quot;Tournament/Competition&quot; = &quot;Competition&quot;)) +
   guides(fill = &quot;none&quot;) +
  labs(
    title = &quot;By Event Type&quot;,
    x = &quot;Event Type&quot;,
    y = &quot;Attendance&quot;) +
  theme_minimal()

plot_borough =
  ggplot(parkevent, aes(x = borough, y = attendance, fill=borough)) +
  geom_violin(trim = FALSE, alpha = 0.5) +
  geom_boxplot(width=0.15) +
  coord_cartesian(ylim = c(0,250)) +
  scale_x_discrete(labels = c(
    &quot;Bronx&quot;        = &quot;BX&quot;,
    &quot;Brooklyn&quot;     = &quot;BKN&quot;,
    &quot;Manhattan&quot;    = &quot;MAN&quot;,
    &quot;Queens&quot;       = &quot;QNS&quot;,
    &quot;Staten Island&quot;= &quot;SI&quot;)) +
  labs(title = &quot;By Borough&quot;, x = &quot;Borough&quot;, y = &quot;Attendance&quot;) +
  guides(fill = &quot;none&quot;) +
  theme_minimal()

plot_location =
  ggplot(parkevent, aes(x = location_type, y = attendance, fill = location_type)) +
  geom_violin(trim = FALSE, alpha = 0.5) +
  geom_boxplot(width = 0.15) +
  coord_cartesian(ylim = c(0,250)) +
  scale_x_discrete(labels = c(
    &quot;Nature Center&quot; = &quot;Nature&quot;,
    &quot;Recreation Center&quot; = &quot;RecCen&quot;,
    &quot;Playground&quot; = &quot;Playground&quot;,
    &quot;Pool&quot; = &quot;Pool&quot;,
    &quot;Park&quot; = &quot;Park&quot;,
    &quot;Other&quot; = &quot;Other&quot;,
    &quot;School&quot; = &quot;School&quot;)) +
  labs(
    title = &quot;By Location Type&quot;,
    x = &quot;Location Type&quot;,
    y = &quot;Attendance&quot;) +
   guides(fill = &quot;none&quot;) +
  theme_minimal()

parkevent_long &lt;- parkevent |&gt; 
  pivot_longer(
    cols = c(kids_friendly, senior_friendly, adults_only),
    names_to  = &quot;audience_type&quot;,
    values_to = &quot;flag&quot;
  ) |&gt; 
  filter(flag) |&gt; 
  select(-flag) |&gt; 
  mutate(
    audience_type = recode(
      audience_type,
      kids_friendly   = &quot;Kids&quot;,
      senior_friendly = &quot;Seniors&quot;,
      adults_only     = &quot;Adults&quot;))

plot_audience =
  ggplot(parkevent_long,
         aes(x = audience_type, y = attendance, fill = audience_type)) +
  geom_violin(trim = FALSE, alpha = 0.5) +
  geom_boxplot(width = 0.15) +
  coord_cartesian(ylim = c(0, 250)) +
  labs(
    title = &quot;By Audience Type&quot;,
    x = &quot;Audience Type&quot;,
    y = &quot;Attendance&quot;) +
  guides(fill = &quot;none&quot;) +
  theme_minimal()

patterns_plot =
  ((plot_season |plot_time| plot_borough) /
    (plot_audience|plot_type| plot_location))+
  plot_annotation(
    title = &quot;Attendance Patterns Across NYC Parks Events&quot;,
    theme = theme())
patterns_plot</code></pre>
<p><img src="data_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Figure displays violin–boxplots of attendance by season, time of day,
borough, event type, aduience type and location type. These plots
summarize both the distribution (violin shape) and central tendency (box
plot) for each category, allowing visual comparison of how attendance
varies across park events. We restricted the y-axis to 0–250 attendees
because most events fall within this range, while a small number of very
large events have much higher attendance. Without this limit, those
extreme values compress the main body of the data and make differences
between typical events difficult to see.</p>
<pre class="r"><code>ggplot(parkevent_long,
       aes(x = month, fill = audience_type)) +
  geom_bar(position = &quot;fill&quot;) </code></pre>
<p><img src="data_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>  labs(
    title = &quot;Audience Composition by Borough&quot;,
    x = &quot;Month&quot;,
    y = &quot;Proportion&quot;,
    fill = &quot;Audience Type&quot;
  ) +
  theme_minimal()</code></pre>
<pre><code>## NULL</code></pre>
<p>This stacked bar chart shows how audience composition varies across
months for NYC park events. Kids-friendly events consistently represent
the largest share throughout the year, especially from April to October,
indicating strong family engagement during warmer months.
Senior-friendly events also maintain a substantial and steady presence,
peaking in early spring and again in late summer. Adults-only events
fluctuate more noticeably, with higher proportions in winter months such
as January and December. Overall, the chart highlights seasonal shifts
in audience needs: family-oriented programming dominates most of the
year, while adult-focused events become relatively more common during
colder months.</p>
<pre class="r"><code>plot_time_season =
  parkevent |&gt;
  group_by(time_period, season) |&gt;
  summarize(mean_attendance = mean(attendance)) |&gt;
  ggplot(aes(x = time_period, 
             y = mean_attendance, 
             color = season, 
             group = season)) +
  geom_line() +
  geom_point() +
  labs(
    title = &quot;Mean Attendance by Time of Day Across Seasons&quot;,
    x = &quot;Time of Day&quot;,
    y = &quot;Mean Attendance&quot;,
    color = &quot;Season&quot;) +
  theme_minimal()</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;time_period&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre class="r"><code>plot_borough_season =
  parkevent |&gt;
  group_by(borough, season) |&gt;
  summarize(mean_attendance = mean(attendance)) |&gt;
  ggplot(aes(x = season, 
             y = mean_attendance, 
             color = borough, 
             group = borough)) +
  geom_line() +
  geom_point() +
   scale_color_brewer(palette = &quot;Dark2&quot;) +  
  labs(
    title = &quot;Mean Attendance by Seasons Across Borough&quot;,
    x = &quot;Season&quot;,
    y = &quot;Mean Attendance&quot;,
    color = &quot;borough&quot;) +
  theme_minimal()</code></pre>
<pre><code>## `summarise()` has grouped output by &#39;borough&#39;. You can override using the
## `.groups` argument.</code></pre>
<pre class="r"><code>Seasonal_plot =
  (plot_time_season / plot_borough_season) +
  plot_annotation(
    title = &quot;Seasonal Attendance Patterns Across NYC Park Events&quot;)

Seasonal_plot</code></pre>
<p><img src="data_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The first plot shows how mean attendance varies by time of day across
seasons. Spring consistently has the highest turnout, especially in the
afternoon, while Winter shows the sharpest decline at midnight. Fall
attendance remains relatively stable across all times, whereas Summer
gradually increases into the evening. The second plot compares mean
attendance by seasons across borough. Staten Island and Queens show the
highest seasonal peaks, particularly in Spring. Brooklyn and Manhattan
maintain moderate attendance across seasons, while the Bronx shows the
lowest and least variable averages. Together, these trends highlight
clear seasonal and geographic differences in NYC park event
engagement.</p>
<pre class="r"><code>plot_calendar =
  ggplot(parkevent, 
         aes(x = month(date, label = TRUE, abbr = TRUE), 
             y = attendance)) +
  geom_point(alpha = 0.2, color = &quot;gray70&quot;) +
  stat_summary(fun = mean, geom = &quot;line&quot;, aes(group = 1),
               color = &quot;cornflowerblue&quot;, size = 1) +
  stat_summary(fun = mean, geom = &quot;point&quot;,
               color = &quot;cornflowerblue&quot;, size = 2) +
  labs(
    title = &quot;Attendance Over the Calendar Year&quot;,
    x = &quot;Month&quot;,
    y = &quot;Attendance&quot;) +
  coord_cartesian(ylim = c(0, 250)) + 
  theme_minimal()</code></pre>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<pre class="r"><code>plot_calendar</code></pre>
<p><img src="data_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>This plot shows how park event attendance varies throughout the
calendar year by combining individual event points with a smoothed
monthly trend line. Grey points display the full distribution of
attendance for all events, allowing visualization of variability within
each month. Monthly averages are overlaid as a blue line to highlight
broader seasonal patterns that daily fluctuations may obscure. The
results show a dip in February, rising attendance during spring, a
slight decline in midsummer, and another increase in October and
December. Using monthly means helps reveal consistent seasonal trends
while still preserving the underlying data distribution for context and
interpretation.</p>
</div>
<div id="modeling-workflow-diagram" class="section level2">
<h2>Modeling Workflow Diagram</h2>
<pre><code>                     ┌──────────────────────────────────┐
                     │  Exploratory Data Analysis (EDA) │
                     │  - Histogram of attendance       │
                     │  - mean–variance check           │
                     │  → Identify skewness &amp; overdispersion
                     └──────────────────────────────────┘
                                     │
                                     ▼
               ┌───────────────────────────────────────────────┐
               │ Univariate Analysis                           │
               │ - Kruskal–Wallis tests for each predictor     │
               │ - Compute η² effect sizes                     │
               │ → Assess which predictors show meaningful     │
               │   variation in attendance                     │
               └───────────────────────────────────────────────┘
                                     │
                                     ▼
         ┌──────────────────────────────────────────────────────────┐
         │ Model Building: Cross-Validated Variable Selection       │
         │ - Define Simple, Medium, Full predictor sets             │
         │ - Monte Carlo CV with RMSE as performance metric         │
         │ → Select predictor set with best out-of-sample RMSE      │
         └──────────────────────────────────────────────────────────┘
                                     │
                                     ▼
         ┌──────────────────────────────────────────────────────────┐
         │ Final Model Fitting                                      │
         │ - Fit Negative Binomial regression using selected vars   │
         │ - Extract IRRs and confidence intervals                  │
         │ → Interpret effect sizes and direction of associations   │
         └──────────────────────────────────────────────────────────┘
                                     │
                                     ▼
               ┌───────────────────────────────────────────────┐
               │ Final Inference &amp; Interpretation              │
               │ - Discuss strongest predictors                │
               │ - Compare event characteristics &amp; attendance  │
               │ - Guide practical recommendations             │
               └───────────────────────────────────────────────┘</code></pre>
<div id="exploratory-distribution-plots" class="section level3">
<h3>Exploratory distribution plots</h3>
<p>Before conducting formal statistical analyses, we examined the
distribution of the outcome variable, attendance, to assess its shape
and variability. Understanding the distribution is essential for
determining whether parametric assumptions are met and for selecting an
appropriate modeling framework.</p>
<pre class="r"><code> a &lt;- ggplot(parkevent, aes(x = attendance)) +
  geom_histogram(bins = 40, fill = &quot;steelblue&quot;, color = &quot;white&quot;) +
  labs(title = &quot;Attendance Distribution (Count)&quot;,
       x = &quot;Attendance&quot;, y = &quot;Count&quot;) +
  theme_minimal()

b &lt;- ggplot(parkevent, aes(x = attendance)) +
  geom_histogram(bins = 40, fill = &quot;tomato&quot;, color = &quot;white&quot;) +
  scale_x_log10() +
  labs(title = &quot;Attendance Distribution (Log Scale)&quot;,
       x = &quot;Attendance (log10 scale)&quot;, y = &quot;Count&quot;) +
  theme_minimal()

a+b</code></pre>
<pre><code>## Warning in scale_x_log10(): log-10 transformation introduced infinite values.</code></pre>
<pre><code>## Warning: Removed 219 rows containing non-finite outside the scale range
## (`stat_bin()`).</code></pre>
<p><img src="data_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>mean_var &lt;- parkevent %&gt;%
  summarise(mean_att = mean(attendance), var_att = var(attendance))

mean_var</code></pre>
<pre><code>##   mean_att  var_att
## 1 74.44136 10191.33</code></pre>
<p>Exploratory plots revealed that attendance is highly right-skewed
with a long tail, and the variance greatly exceeds the mean, indicating
overdispersion. These characteristics justify the use of non-parametric
tests in the univariate stage and a Negative Binomial model for the
final multivariable analysis.</p>
</div>
<div id="univariate-analysis" class="section level3">
<h3>Univariate Analysis</h3>
<p>We first examined whether attendance differed across levels of each
categorical predictor (season, time of day, borough, event type,
location type, and audience-related indicators) using the Kruskal–Wallis
test, a non-parametric method appropriate for skewed count outcomes. For
each variable, we also computed an η² effect size to quantify the
magnitude of group differences. These results provide an initial
assessment of which predictors meaningfully explain variation in
attendance and should be considered in subsequent multivariable
modeling.</p>
<pre class="r"><code>library(MASS)</code></pre>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:patchwork&#39;:
## 
##     area</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<pre class="r"><code>library(modelr)</code></pre>
<pre><code>## 
## Attaching package: &#39;modelr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:broom&#39;:
## 
##     bootstrap</code></pre>
<pre class="r"><code>predictors &lt;- c(&quot;season&quot;, &quot;time_period&quot;, &quot;borough&quot;,
                &quot;event_type&quot;, &quot;location_type&quot;,
                &quot;kids_friendly&quot;, &quot;senior_friendly&quot;, &quot;adults_only&quot;)

#Function to compute eta-squared for KW
eta_kw &lt;- function(x, g){
  kw &lt;- kruskal.test(x ~ g)
  H  &lt;- kw$statistic
  k  &lt;- length(unique(g))
  n  &lt;- length(x)
  eta2 &lt;- as.numeric((H - k + 1) / (n - k))
  return(eta2)
}

# Run Kruskal–Wallis tests for all predictors
kw_results &lt;- map_df(predictors, ~ {
  form &lt;- as.formula(paste(&quot;attendance ~&quot;, .x))
  
  kt  &lt;- broom::tidy(kruskal.test(form, data = parkevent))
  eta2 &lt;- eta_kw(parkevent$attendance, parkevent[[.x]])
  
  kt |&gt; 
    mutate(variable = .x,
           eta2 = eta2)
})

# Classify effect sizes ----
kw_results &lt;- kw_results |&gt; 
  mutate(effect_strength = case_when(
    eta2 &gt;= 0.14 ~ &quot;large&quot;,
    eta2 &gt;= 0.06 ~ &quot;medium&quot;,
    eta2 &gt;= 0.01 ~ &quot;small&quot;,
    TRUE ~ &quot;very small&quot;
  ))

kw_results |&gt;
  dplyr::select (variable, p.value, effect_strength)</code></pre>
<pre><code>## # A tibble: 8 × 3
##   variable         p.value effect_strength
##   &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;          
## 1 season          3.73e-10 small          
## 2 time_period     3.22e-10 small          
## 3 borough         1.29e-29 small          
## 4 event_type      1.31e-39 medium         
## 5 location_type   2.51e-50 medium         
## 6 kids_friendly   1.36e- 8 small          
## 7 senior_friendly 1.02e- 9 small          
## 8 adults_only     1.10e- 8 small</code></pre>
<p>Across all predictors, the Kruskal–Wallis tests indicated
statistically significant differences in attendance (p &lt; 0.05), with
effect sizes ranging from very small to medium. Variables with medium η²
values (event type and location type) show stronger associations with
attendance and were prioritized for inclusion in the multivariable
model.</p>
<p>To evaluate their combined predictive value and adjust for potential
confounding, we proceeded to build multivariable models.</p>
</div>
<div id="multivariable-model-negative-binomial-regression"
class="section level3">
<h3>Multivariable Model: Negative Binomial Regression</h3>
<p>To identify the predictors that best explain variation in attendance,
we compared several candidate models using cross-validated RMSE, an
unbiased measure of out-of-sample predictive performance. We used
log-linear models for this stage because they are computationally stable
and well-suited for repeated Monte Carlo cross-validation. Based on the
RMSE comparison, we selected the most predictive set of variables and
then refit the final model using Negative Binomial regression, which is
appropriate for inference with overdispersed count outcomes such as
attendance.</p>
<pre class="r"><code>#Define candidate models
form_simple &lt;- log(attendance + 1) ~ event_type + location_type

form_medium &lt;- log(attendance + 1) ~ season + time_period + borough +
  event_type + location_type

form_full &lt;- log(attendance + 1) ~ season + time_period + borough +
  event_type + location_type + kids_friendly + senior_friendly + adults_only

#cross-validated RMSE
cv_rmse &lt;- function(formula, data, n_splits = 50, test_prop = 0.1) {
  set.seed(123)
  
cv &lt;- crossv_mc(data, n_splits, test = test_prop)
  
cv &lt;- cv %&gt;%
    mutate(
      model = map(train, ~ lm(formula, data = .x)),
      rmse  = map2_dbl(model, test, ~ rmse(.x, .y))
    )
  
mean(cv$rmse)
}

rmse_simple &lt;- cv_rmse(form_simple, parkevent, n_splits = 50, test_prop = 0.1)
rmse_medium &lt;- cv_rmse(form_medium, parkevent, n_splits = 50, test_prop = 0.1)
rmse_full   &lt;- cv_rmse(form_full,   parkevent, n_splits = 50, test_prop = 0.1)

cv_results &lt;- tibble(
  model     = c(&quot;Simple&quot;, &quot;Medium&quot;, &quot;Full&quot;),
  mean_RMSE = c(rmse_simple, rmse_medium, rmse_full)
)

cv_results</code></pre>
<pre><code>## # A tibble: 3 × 2
##   model  mean_RMSE
##   &lt;chr&gt;      &lt;dbl&gt;
## 1 Simple      1.46
## 2 Medium      1.43
## 3 Full        1.43</code></pre>
<p>Cross-validated RMSE values were similar across the three candidate
models, with the Full model achieving the lowest prediction error (RMSE
= 1.4263). Although the difference is modest, the Full model provided
the best out-of-sample predictive performance and was therefore selected
for the final analysis.</p>
<p>Using the selected predictor set, we fit our final model with a
Negative Binomial regression:</p>
<pre class="r"><code>model_nb &lt;- glm.nb(
  attendance ~ season + time_period + borough +
    event_type + location_type + kids_friendly + senior_friendly + adults_only,
  data = parkevent
)

summary(model_nb)</code></pre>
<pre><code>## 
## Call:
## glm.nb(formula = attendance ~ season + time_period + borough + 
##     event_type + location_type + kids_friendly + senior_friendly + 
##     adults_only, data = parkevent, init.theta = 0.708183943, 
##     link = log)
## 
## Coefficients:
##                                   Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                       3.354459   0.521364   6.434 1.24e-10 ***
## seasonSummer                     -0.115167   0.090012  -1.279 0.200734    
## seasonFall                       -0.075548   0.094641  -0.798 0.424723    
## seasonWinter                     -0.313277   0.154062  -2.033 0.042008 *  
## time_periodAfternoon              0.298264   0.089379   3.337 0.000847 ***
## time_periodNight                  0.226237   0.095108   2.379 0.017373 *  
## time_periodMidnight               0.157769   0.104417   1.511 0.130803    
## boroughBrooklyn                   0.143682   0.086319   1.665 0.096006 .  
## boroughManhattan                  0.516853   0.073695   7.013 2.33e-12 ***
## boroughQueens                     0.247231   0.074676   3.311 0.000931 ***
## boroughStaten Island              0.366326   0.085857   4.267 1.98e-05 ***
## event_typeCommunity Based Event   0.267910   0.070198   3.816 0.000135 ***
## event_typeLocal Event            -0.009123   0.095912  -0.095 0.924218    
## event_typeOpen House              0.231935   0.411226   0.564 0.572749    
## event_typeTournament/Competition  0.574397   0.371595   1.546 0.122163    
## location_typeOther                0.746571   0.471910   1.582 0.113645    
## location_typePark                 0.684760   0.462320   1.481 0.138570    
## location_typePlayground           0.261105   0.466260   0.560 0.575480    
## location_typePool                -0.608642   0.469137  -1.297 0.194505    
## location_typeRecreation Center    0.255496   0.465275   0.549 0.582918    
## location_typeSchool               1.427969   0.477940   2.988 0.002810 ** 
## kids_friendlyTRUE                -0.070456   0.215035  -0.328 0.743176    
## senior_friendlyTRUE              -0.022038   0.066679  -0.331 0.741010    
## adults_onlyTRUE                  -0.817763   0.237422  -3.444 0.000572 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(0.7082) family taken to be 1)
## 
##     Null deviance: 3435.3  on 2446  degrees of freedom
## Residual deviance: 2957.5  on 2423  degrees of freedom
## AIC: 25225
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  0.7082 
##           Std. Err.:  0.0193 
## 
##  2 x log-likelihood:  -25175.4960</code></pre>
<pre class="r"><code>irr_table &lt;- tidy(model_nb, conf.int = TRUE, exponentiate = TRUE)
irr_table</code></pre>
<pre><code>## # A tibble: 24 × 7
##    term                 estimate std.error statistic  p.value conf.low conf.high
##    &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
##  1 (Intercept)            28.6      0.521      6.43  1.24e-10   11.4      89.1  
##  2 seasonSummer            0.891    0.0900    -1.28  2.01e- 1    0.744     1.06 
##  3 seasonFall              0.927    0.0946    -0.798 4.25e- 1    0.769     1.11 
##  4 seasonWinter            0.731    0.154     -2.03  4.20e- 2    0.544     0.997
##  5 time_periodAfternoon    1.35     0.0894     3.34  8.47e- 4    1.12      1.61 
##  6 time_periodNight        1.25     0.0951     2.38  1.74e- 2    1.03      1.51 
##  7 time_periodMidnight     1.17     0.104      1.51  1.31e- 1    0.950     1.44 
##  8 boroughBrooklyn         1.15     0.0863     1.66  9.60e- 2    0.979     1.37 
##  9 boroughManhattan        1.68     0.0737     7.01  2.33e-12    1.46      1.92 
## 10 boroughQueens           1.28     0.0747     3.31  9.31e- 4    1.11      1.48 
## # ℹ 14 more rows</code></pre>
<p>In this model, attendance is modeled as a function of season, time of
day, borough, event type, location type, and audience indicators. We
exponentiate the coefficients to obtain incidence rate ratios (IRRs) and
95% confidence intervals, which quantify the multiplicative change in
expected attendance associated with each predictor while holding the
others constant.</p>
<p>The Negative Binomial model shows that several event characteristics
are strongly associated with attendance. Compared with spring events,
winter events have significantly lower expected attendance (IRR = 0.73,
95% CI: 0.54–1.00), while summer and fall do not differ significantly
from spring.</p>
<p>Afternoon and night events attract more participants than morning
events (Afternoon: IRR = 1.35, 95% CI: 1.12–1.61; Night: IRR = 1.25, 95%
CI: 1.03–1.51). Relative to Bronx, events in Manhattan, Queens, and
Staten Island show higher attendance (IRRs ≈ 1.28–1.68), with Manhattan
having the largest effect.</p>
<p>Community-based events have higher attendance than Agency Produced
events (IRR = 1.31, 95% CI: 1.14–1.50), and events held in schools and
parks are particularly well-attended (School: IRR = 4.17, 95% CI:
1.43–9.64; Park: IRR = 1.98, 95% CI: 1.00–4.38).</p>
<p>For the audience, adults-only events draw substantially fewer
participants than events that are open to children or seniors (IRR =
0.44, 95% CI: 0.27–0.69), while the kids-friendly and senior-friendly
indicators are not individually significant after adjustment for other
covariates.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
