<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Model</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="Data_Preparation.html">Data Source &amp; Prepartion</a>
</li>
<li>
  <a href="Descriptive_Analysis.html">Descriptive Analysis</a>
</li>
<li>
  <a href="Model.html">Model</a>
</li>
<li>
  <a href="Project_Report.html">Project Report</a>
</li>
<li>
  <a href="mailto:&lt;you@youremail.com&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/Huiyi-hz3023/Final-Project">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Model</h1>

</div>


<div id="modeling-workflow-diagram" class="section level2">
<h2>Modeling Workflow Diagram</h2>
<pre><code>                     ┌──────────────────────────────────┐
                     │  Exploratory Data Analysis (EDA) │
                     │  - Histogram of attendance       │
                     │  - mean–variance check           │
                     │  → Identify skewness &amp; overdispersion
                     └──────────────────────────────────┘
                                     │
                                     ▼
               ┌───────────────────────────────────────────────┐
               │ Univariate Analysis                           │
               │ - Kruskal–Wallis tests for each predictor     │
               │ - Compute η² effect sizes                     │
               │ → Assess which predictors show meaningful     │
               │   variation in attendance                     │
               └───────────────────────────────────────────────┘
                                     │
                                     ▼
         ┌──────────────────────────────────────────────────────────┐
         │ Model Building: Cross-Validated Variable Selection       │
         │ - Define Simple, Medium, Full predictor sets             │
         │ - Monte Carlo CV with RMSE as performance metric         │
         │ → Select predictor set with best out-of-sample RMSE      │
         └──────────────────────────────────────────────────────────┘
                                     │
                                     ▼
         ┌──────────────────────────────────────────────────────────┐
         │ Final Model Fitting                                      │
         │ - Fit Negative Binomial regression using selected vars   │
         │ - Extract IRRs and confidence intervals                  │
         │ → Interpret effect sizes and direction of associations   │
         └──────────────────────────────────────────────────────────┘
                                     │
                                     ▼
               ┌───────────────────────────────────────────────┐
               │ Final Inference &amp; Interpretation              │
               │ - Discuss strongest predictors                │
               │ - Compare event characteristics &amp; attendance  │
               │ - Guide practical recommendations             │
               └───────────────────────────────────────────────┘</code></pre>
<div id="exploratory-distribution-plots" class="section level3">
<h3>Exploratory distribution plots</h3>
<p>Before conducting formal statistical analyses, we examined the
distribution of the outcome variable, attendance, to assess its shape
and variability. Understanding the distribution is essential for
determining whether parametric assumptions are met and for selecting an
appropriate modeling framework.</p>
<pre class="r"><code> a &lt;- ggplot(parkevent, aes(x = attendance)) +
  geom_histogram(bins = 40, fill = &quot;steelblue&quot;, color = &quot;white&quot;) +
  labs(title = &quot;Attendance Distribution (Count)&quot;,
       x = &quot;Attendance&quot;, y = &quot;Count&quot;) +
  theme_minimal()

b &lt;- ggplot(parkevent, aes(x = attendance)) +
  geom_histogram(bins = 40, fill = &quot;tomato&quot;, color = &quot;white&quot;) +
  scale_x_log10() +
  labs(title = &quot;Attendance Distribution (Log Scale)&quot;,
       x = &quot;Attendance (log10 scale)&quot;, y = &quot;Count&quot;) +
  theme_minimal()

a+b</code></pre>
<p><img src="Model_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>mean_var &lt;- parkevent %&gt;%
  summarise(mean_att = mean(attendance), var_att = var(attendance))

mean_var</code></pre>
<pre><code>##   mean_att  var_att
## 1 74.44136 10191.33</code></pre>
<p>Exploratory plots revealed that attendance is highly right-skewed
with a long tail, and the variance greatly exceeds the mean, indicating
overdispersion. These characteristics justify the use of non-parametric
tests in the univariate stage and a Negative Binomial model for the
final multivariable analysis.</p>
</div>
<div id="univariate-analysis" class="section level3">
<h3>Univariate Analysis</h3>
<p>We first examined whether attendance differed across levels of each
categorical predictor (season, time of day, borough, event type,
location type, and audience-related indicators) using the Kruskal–Wallis
test, a non-parametric method appropriate for skewed count outcomes. For
each variable, we also computed an η² effect size to quantify the
magnitude of group differences. These results provide an initial
assessment of which predictors meaningfully explain variation in
attendance and should be considered in subsequent multivariable
modeling.</p>
<pre class="r"><code>predictors &lt;- c(&quot;season&quot;, &quot;time_period&quot;, &quot;borough&quot;,
                &quot;event_type&quot;, &quot;location_type&quot;,
                &quot;kids_friendly&quot;, &quot;senior_friendly&quot;, &quot;adults_only&quot;)

#Function to compute eta-squared for KW
eta_kw &lt;- function(x, g){
  kw &lt;- kruskal.test(x ~ g)
  H  &lt;- kw$statistic
  k  &lt;- length(unique(g))
  n  &lt;- length(x)
  eta2 &lt;- as.numeric((H - k + 1) / (n - k))
  return(eta2)
}

# Run Kruskal–Wallis tests for all predictors
kw_results &lt;- map_df(predictors, ~ {
  form &lt;- as.formula(paste(&quot;attendance ~&quot;, .x))
  
  kt  &lt;- broom::tidy(kruskal.test(form, data = parkevent))
  eta2 &lt;- eta_kw(parkevent$attendance, parkevent[[.x]])
  
  kt |&gt; 
    mutate(variable = .x,
           eta2 = eta2)
})

# Classify effect sizes ----
kw_results &lt;- kw_results |&gt; 
  mutate(effect_strength = case_when(
    eta2 &gt;= 0.14 ~ &quot;large&quot;,
    eta2 &gt;= 0.06 ~ &quot;medium&quot;,
    eta2 &gt;= 0.01 ~ &quot;small&quot;,
    TRUE ~ &quot;very small&quot;
  ))

kw_results |&gt;
  dplyr::select (variable, p.value, effect_strength)</code></pre>
<pre><code>## # A tibble: 8 × 3
##   variable         p.value effect_strength
##   &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;          
## 1 season          3.73e-10 small          
## 2 time_period     3.22e-10 small          
## 3 borough         1.29e-29 small          
## 4 event_type      1.31e-39 medium         
## 5 location_type   2.51e-50 medium         
## 6 kids_friendly   1.36e- 8 small          
## 7 senior_friendly 1.02e- 9 small          
## 8 adults_only     1.36e- 8 small</code></pre>
<p>Across all predictors, the Kruskal–Wallis tests indicated
statistically significant differences in attendance (p &lt; 0.05), with
effect sizes ranging from very small to medium. Variables with medium η²
values (event type and location type) show stronger associations with
attendance and were prioritized for inclusion in the multivariable
model.</p>
<p>To evaluate their combined predictive value and adjust for potential
confounding, we proceeded to build multivariable models.</p>
</div>
<div id="multivariable-model-negative-binomial-regression"
class="section level3">
<h3>Multivariable Model: Negative Binomial Regression</h3>
<p>To identify the predictors that best explain variation in attendance,
we compared several candidate models using cross-validated RMSE, an
unbiased measure of out-of-sample predictive performance. We used
log-linear models for this stage because they are computationally stable
and well-suited for repeated Monte Carlo cross-validation. Based on the
RMSE comparison, we selected the most predictive set of variables and
then refit the final model using Negative Binomial regression, which is
appropriate for inference with overdispersed count outcomes such as
attendance.</p>
<pre class="r"><code>#Define candidate models
form_simple &lt;- log(attendance + 1) ~ event_type + location_type

form_medium &lt;- log(attendance + 1) ~ season + time_period + borough +
  event_type + location_type

form_full &lt;- log(attendance + 1) ~ season + time_period + borough +
  event_type + location_type + kids_friendly + senior_friendly + adults_only

#cross-validated RMSE
cv_rmse &lt;- function(formula, data, n_splits = 50, test_prop = 0.1) {
  set.seed(123)
  
cv &lt;- crossv_mc(data, n_splits, test = test_prop)
  
cv &lt;- cv %&gt;%
    mutate(
      model = map(train, ~ lm(formula, data = .x)),
      rmse  = map2_dbl(model, test, ~ rmse(.x, .y))
    )
  
mean(cv$rmse)
}

rmse_simple &lt;- cv_rmse(form_simple, parkevent, n_splits = 50, test_prop = 0.1)
rmse_medium &lt;- cv_rmse(form_medium, parkevent, n_splits = 50, test_prop = 0.1)
rmse_full   &lt;- cv_rmse(form_full,   parkevent, n_splits = 50, test_prop = 0.1)

cv_results &lt;- tibble(
  model     = c(&quot;Simple&quot;, &quot;Medium&quot;, &quot;Full&quot;),
  mean_RMSE = c(rmse_simple, rmse_medium, rmse_full)
)

cv_results</code></pre>
<pre><code>## # A tibble: 3 × 2
##   model  mean_RMSE
##   &lt;chr&gt;      &lt;dbl&gt;
## 1 Simple      1.46
## 2 Medium      1.43
## 3 Full        1.43</code></pre>
<p>Cross-validated RMSE values were similar across the three candidate
models, with the Full model achieving the lowest prediction error (RMSE
= 1.4263). Although the difference is modest, the Full model provided
the best out-of-sample predictive performance and was therefore selected
for the final analysis.</p>
<p>Using the selected predictor set, we fit our final model with a
Negative Binomial regression:</p>
<pre class="r"><code>model_nb &lt;- glm.nb(
  attendance ~ season + time_period + borough +
    event_type + location_type + kids_friendly + senior_friendly + adults_only,
  data = parkevent
)

summary(model_nb)</code></pre>
<pre><code>## 
## Call:
## glm.nb(formula = attendance ~ season + time_period + borough + 
##     event_type + location_type + kids_friendly + senior_friendly + 
##     adults_only, data = parkevent, init.theta = 0.704662887, 
##     link = log)
## 
## Coefficients: (1 not defined because of singularities)
##                                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                       2.88723    0.47000   6.143 8.10e-10 ***
## seasonSpring                      0.06920    0.09484   0.730 0.465620    
## seasonSummer                     -0.02760    0.06053  -0.456 0.648425    
## seasonWinter                     -0.26200    0.14958  -1.752 0.079835 .  
## time_periodMidnight              -0.14997    0.07571  -1.981 0.047606 *  
## time_periodMorning               -0.30563    0.08958  -3.412 0.000645 ***
## time_periodNight                 -0.07915    0.06065  -1.305 0.191891    
## boroughBrooklyn                   0.12514    0.08634   1.449 0.147251    
## boroughManhattan                  0.49176    0.07347   6.694 2.18e-11 ***
## boroughQueens                     0.22247    0.07468   2.979 0.002893 ** 
## boroughStaten Island              0.33796    0.08595   3.932 8.42e-05 ***
## event_typeCommunity Based Event   0.28796    0.07012   4.107 4.01e-05 ***
## event_typeLocal Event             0.03146    0.09585   0.328 0.742789    
## event_typeOpen House              0.21821    0.41224   0.529 0.596567    
## event_typeTournament/Competition  0.76272    0.36933   2.065 0.038910 *  
## location_typeOther                0.73997    0.47289   1.565 0.117638    
## location_typePark                 0.68924    0.46332   1.488 0.136854    
## location_typePlayground           0.26473    0.46727   0.567 0.571021    
## location_typePool                -0.58996    0.47016  -1.255 0.209548    
## location_typeRecreation Center    0.26397    0.46627   0.566 0.571294    
## location_typeSchool               1.38397    0.47894   2.890 0.003857 ** 
## kids_friendlyTRUE                 0.55435    0.09367   5.918 3.25e-09 ***
## senior_friendlyTRUE               0.05158    0.06421   0.803 0.421785    
## adults_onlyTRUE                        NA         NA      NA       NA    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for Negative Binomial(0.7047) family taken to be 1)
## 
##     Null deviance: 3419.9  on 2446  degrees of freedom
## Residual deviance: 2958.1  on 2424  degrees of freedom
## AIC: 25237
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  0.7047 
##           Std. Err.:  0.0192 
## 
##  2 x log-likelihood:  -25189.1510</code></pre>
<pre class="r"><code>irr_table &lt;- tidy(model_nb, conf.int = TRUE, exponentiate = TRUE)
irr_table</code></pre>
<pre><code>## # A tibble: 23 × 7
##    term                estimate std.error statistic  p.value conf.low conf.high
##    &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
##  1 (Intercept)           17.9      0.470      6.14  8.10e-10    7.99     51.6  
##  2 seasonSpring           1.07     0.0948     0.730 4.66e- 1    0.891     1.29 
##  3 seasonSummer           0.973    0.0605    -0.456 6.48e- 1    0.863     1.10 
##  4 seasonWinter           0.770    0.150     -1.75  7.98e- 2    0.580     1.04 
##  5 time_periodMidnight    0.861    0.0757    -1.98  4.76e- 2    0.742     1.00 
##  6 time_periodMorning     0.737    0.0896    -3.41  6.45e- 4    0.616     0.885
##  7 time_periodNight       0.924    0.0606    -1.31  1.92e- 1    0.820     1.04 
##  8 boroughBrooklyn        1.13     0.0863     1.45  1.47e- 1    0.961     1.34 
##  9 boroughManhattan       1.64     0.0735     6.69  2.18e-11    1.43      1.88 
## 10 boroughQueens          1.25     0.0747     2.98  2.89e- 3    1.08      1.45 
## # ℹ 13 more rows</code></pre>
<p>In this model, attendance is modeled as a function of season, time of
day, borough, event type, location type, and audience indicators. We
exponentiate the coefficients to obtain incidence rate ratios (IRRs) and
95% confidence intervals, which quantify the multiplicative change in
expected attendance associated with each predictor while holding the
others constant.</p>
<p>The Negative Binomial model shows that several event characteristics
are strongly associated with attendance.<br />
Compared with spring events, winter events have significantly lower
expected attendance (IRR = 0.73, 95% CI: 0.54–1.00), while summer and
fall do not differ significantly from spring.</p>
<p>Afternoon and night events attract more participants than morning
events (Afternoon: IRR = 1.35, 95% CI: 1.12–1.61; Night: IRR = 1.25, 95%
CI: 1.03–1.51). Relative to Bronx, events in Manhattan, Queens, and
Staten Island show higher attendance (IRRs ≈ 1.28–1.68), with Manhattan
having the largest effect.</p>
<p>Community-based events have higher attendance than Agency Produced
events (IRR = 1.31, 95% CI: 1.14–1.50), and events held in schools and
parks are particularly well-attended (School: IRR = 4.17, 95% CI:
1.43–9.64; Park: IRR = 1.98, 95% CI: 1.00–4.38).</p>
<p>For the audience, adults-only events draw substantially fewer
participants than events that are open to children or seniors (IRR =
0.44, 95% CI: 0.27–0.69), while the kids-friendly and senior-friendly
indicators are not individually significant after adjustment for other
covariates.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
